# Site settings
title: Emma Maria Karayiannis
email: emma.karayiannis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Hi I'm Emma! I am a frontend developer from the UK. 
 By trade I theme Drupal sites. In my spare time I explore the world.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: emma_maria88
drupal_username: emma.maria
skype_username: emma.karayiannis

# Build settings
markdown: kramdown

# Collections
collections:
- articles
- presentations
- projects
- upcomings
